all:
    ./jobOne.sh > master.txt
    echo -e "\n DONE \n" >> master.txt
    ./jobTwo.sh >> master.txt
    ./nameOne.sh > names.txt
    echo -e "\n DONE \n" >> master.txt
    ./nameTwo.sh >> names.txt